---
image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v1.0.0

platform: linux

inputs:
  - name: ipsec-addon
  - name: bbl-state
  - name: vars-store
  - name: deployment
  - name: pcf-networking-ci

outputs:
- name: updated-vars-store

run:
  path: pcf-networking-ci/tasks/add-ipsec

params:
  BBL_STATE_DIR: ~
  MANIFEST_FILE: ~
  VARS_STORE_FILE: ~
